# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
        - "peer0.org1.example.com:192.168.0.101"
        #- "peer0.org2.example.com:192.168.0.102"
        #- "peer0.org3.example.com:192.168.0.132"
        #- "peer0.org4.example.com:192.168.0.134"
        #- "peer0.org5.example.com:192.168.0.138"
        #- "peer0.org6.example.com:192.168.0.140"
        #- "peer0.org7.example.com:192.168.0.141"
        #- "peer0.org8.example.com:192.168.0.142"
        #- "peer0.org9.example.com:192.168.0.151"
        - "orderer.example.com:192.168.0.152"
        - "orderer2.example.com:192.168.0.153"
        - "orderer3.example.com:192.168.0.154"
        - "orderer4.example.com:192.168.0.155"
        - "orderer5.example.com:192.168.0.156"
        - "orderer6.example.com:192.168.0.121"
        - "orderer7.example.com:192.168.0.123"
        - "orderer8.example.com:192.168.0.124"
        - "orderer9.example.com:192.168.0.125"
        #- "orderer10.example.com:192.168.0.126"
        #- "orderer11.example.com:192.168.0.127"
        #- "orderer12.example.com:192.168.0.131"
        #- "orderer13.example.com:192.168.0.132"
        #- "orderer14.example.com:192.168.0.135"
        #- "orderer15.example.com:192.168.0.136"
    networks:
      - byfn
