# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.4"

volumes:
  orderer3.example.com:

networks:
  byfn:

services:

  orderer3.example.com:
    container_name: orderer3.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    #cpuset: "0,1,2,3"
    #cpuset: "0,1,2,3,4,5,6,7"
    #blkio_config:
    #  device_write_iops:
    #    - path: /dev/sda
    #      rate: 40
    #blkio_config:
    #  device_write_iops:
    #    - path: /dev/sda
    #      rate: 40
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    #extends:
    #  file: base/peer-base.yaml
    #  service: orderer-base
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.example.com:/var/hyperledger/production/orderer
    extra_hosts:
        - "peer0.org1.example.com:192.168.0.101"
        #- "peer0.org2.example.com:192.168.0.102"
        #- "peer0.org3.example.com:192.168.0.132"
        #- "peer0.org4.example.com:192.168.0.134"
        #- "peer0.org5.example.com:192.168.0.138"
        #- "peer0.org6.example.com:192.168.0.140"
        #- "peer0.org7.example.com:192.168.0.141"
        #- "peer0.org8.example.com:192.168.0.142"
        #- "peer0.org9.example.com:192.168.0.151"
        - "orderer.example.com:192.168.0.152"
        - "orderer2.example.com:192.168.0.153"
        - "orderer3.example.com:192.168.0.154"
        - "orderer4.example.com:192.168.0.155"
        - "orderer5.example.com:192.168.0.156"
        - "orderer6.example.com:192.168.0.121"
        - "orderer7.example.com:192.168.0.123"
        - "orderer8.example.com:192.168.0.124"
        - "orderer9.example.com:192.168.0.125"
        - "orderer10.example.com:192.168.0.126"
        - "orderer11.example.com:192.168.0.127"
        - "orderer12.example.com:192.168.0.131"
        - "orderer13.example.com:192.168.0.132"
        - "orderer14.example.com:192.168.0.135"
        - "orderer15.example.com:192.168.0.136"
    ports:
      - 7050:7050
    networks:
      - byfn
